import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import home_page_img from "../public/home_page_img.jpg";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Navbar />
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex justify-center items-center h-screen">
        <figure class="max-w-lg">
          <img
            class=" rounded-lg"
            src="/home_page_img.jpg"
            alt="image description"
          />
          <figcaption class="mt-2 text-sm text-center text-gray-500 dark:text-gray-400">
            Image caption
          </figcaption>
        </figure>
      </div>
      <Footer />
    </>
  );
}
